### ISSUE TITLE
Allow specifying bottom / "hover height" for rectangles

### ISSUE THREAD

**Issue by juliusv** [elchininet/isometric#59]
It would be cool to enable "hovering" rectangles (or just multiple rectangles on top of each other, and thus boxes on top of each other) in an easier way by making the bottom offset of a rectangle configurable.

**Comment by elchininet** [comment]
Hi @juliusv,
I don‘t understand your request. Please, could you elaborate more?
Regards

**Comment by juliusv** [comment]
Ah sorry, I looked more at it again, and what I want is already possible with the current `height` and `top` parameters (that is, setting `top` doesn't actually set the top of the rectangle, but the bottom, i.e. by how much the rectangle gets "lifted" off the ground). Closing this then.

**Comment by elchininet** [comment]
Now I understand what you where searching. It is not exactly that `top` means `bottom`. Let me try to explain it:

* Rectangles are created by default in the `{0;0;0}` coordinates
* Depending on the plane, this coordinate es located in a different corner of the rectangle
* The `top` value it is just the translation in the top axis relative to the `{0;0;0}` coordinates
* 
Take a look at [how the isometric-css library coordinates work](https://elchininet.github.io/isometric-css/knowing-the-basics) because it is the same in that library.

Regards

**Comment by juliusv** [comment]
Ah, thanks for the clarification! Yeah, isometric coordinates are still confusing to me :)
